- .gitignore
- contracts/DataTypes.sol
- contracts/UniversalDecisionContract.sol
- contracts/Utils.sol
- migrations/2_deploy_contracts.js
- package-lock.json
- package.json
Add Universal Decision Contract
> Universal Decision Contract

- contracts/CommitmentContract.sol
> Add blockNumber to commitment contract

- migrations/2_deploy_contracts.js
deploy script is missing the parameter what TestPredict contract needs.
> fix missing constructor parameter

- .gitignore
- contracts/DataTypes.sol
- contracts/Predicate/AtomicPredicate.sol
- contracts/Predicate/LogicalConnective.sol
- contracts/Predicate/NotPredicate.sol
- contracts/Predicate/OperatorPredicate.sol
- contracts/Predicate/TestPredicate.sol
- contracts/UniversalAdjudicationContract.sol
- contracts/Utils.sol
- package-lock.json
- package.json
- test/UniversalDecisionContract.test.js
Update dispute logic of Adjudication Contract.
* Add challenge to UAC
* Add isValidChallenge to predicates
* Add interfaces of predicate types
Close #11 
Close #23
> Updated dispute logic #23

- contracts/CommitmentContract.sol
- test/CommitmentContract.test.js
Updating CommitmentContract and adding spec.
- adding modifier to limit submitting permission
- storing Merle Root to storage
Close #28
> Update CommitmentContract #28

- .travis.yml
- contracts/Predicate/ForAllSuchThatQuantifier.sol
- contracts/Utils.sol
- package-lock.json
- test/ForAllSuchThatQuantifier.test.ts
This is the version of ForAllSuchThatQuantifier for "quantifier is general".
Close #10
> Add ForAllSuchThatQuantifier.sol and test code #10

- contracts/CommitmentContract.sol
- contracts/DataTypes.sol
- package-lock.json
- test/CommitmentContract.test.ts
> feat(contracts): Implement verifyInclusion method in CommitmentContract

- contracts/Library/ECRecover.sol
- contracts/Predicate/Atomic/IsValidSignaturePredicate.sol
- contracts/Predicate/Atomic/TestPredicate.sol
- contracts/UniversalAdjudicationContract.sol
- contracts/Utils.sol
- contracts/test/MockAdjudicatorContract.sol
- test/predicate/atomic/IsValidSignaturePredicate.test.ts
Adding 3 components which are IsValidSignaturePredicate and its test code and ECRecover library.
> Add IsValidSignaturePredicate.sol and its test code

- contracts/Predicate/AndPredicate.sol
- contracts/Predicate/ForAllSuchThatQuantifier.sol
- contracts/Predicate/LogicalConnective.sol
- contracts/Predicate/NotPredicate.sol
- contracts/test/MockChallenge.sol
- test/AndPredicate.test.ts
- test/ForAllSuchThatQuantifier.test.ts
The test code of logical connective shouldn't depend on UAC.
> Clean test code of logical connective to use Mock Adjudicator Contract

- contracts/Predicate/Atomic/VerifyInclusionPredicate.sol
- contracts/test/MockAdjudicatorContract.sol
- contracts/test/MockCommitmentContract.sol
- test/predicate/atomic/VerifyInclusionPredicalte.test.ts
Adding VerifyInclusionPredicate to verify inclusion in Double-Layer tree.
Close #50
> feat: add VerifyInclusionPredicate #50

- contracts/DataTypes.sol
- contracts/DepositContract.sol
- test/DepositContract.test.ts
merge `CheckpointFinalized` and `LogCheckpoint`.
close #68
> merge events

- contracts/Predicate/Atomic/IsValidSignaturePredicate.sol
- contracts/Predicate/Atomic/TestPredicate.sol
- contracts/Predicate/CompiledPredicate.sol
- contracts/UniversalAdjudicationContract.sol
- contracts/Utils.sol
- test/AndPredicate.test.ts
- test/DepositContract.test.ts
- test/ForAllSuchThatQuantifier.test.ts
- test/UniversalDecisionContract.test.ts
- test/helpers/utils.ts
- test/predicate/standard/IsValidStateTransitionPredicate.test.ts
split from #67 
* adding CompiledPredicate interface
* adding helper functions to Utils contract
* adding helper functions for test
> clean: clean interface and test code

- contracts/DepositContract.sol
- test/DepositContract.test.ts
fixing deposit to avoid overflow of `totalDeposited`.
> fix: fix deposit to avoid overflow using SafeMath

- contracts/DataTypes.sol
- contracts/DepositContract.sol
- contracts/Library/Deserializer.sol
- contracts/PlasmaETH.sol
- contracts/test/MockDepositContract.sol
- contracts/test/MockToken.sol
- scripts/deploy.ts
- test/DepositContract.test.ts
- test/PlasmaETH.test.ts
This PR is required for "Deposit flow" milestone.
**adding PlasmaETH**
PlasmaETH is ERC20 wrapping ether.
* adding PlasmaETH ERC20 token which has deposit method
* modifying deploy script
* fixing StateUpdate deserializer 
* fixing StateUpdate data type following https://github.com/cryptoeconomicslab/wakkanay-ethereum-plasma/blob/master/src/types/StateUpdate.ts#L13
> feat: add PlasmaETH

- contracts/CommitmentContract.sol
- contracts/DataTypes.sol
- test/CommitmentContract.test.ts
- test/predicate/atomic/VerifyInclusionPredicalte.test.ts
checking the overwrap of token address.
* fixing verification logic to check overwrap of address
* add "required address must not exceed the implicit address" exception
* leafStart -> leafIndex
* add leafIndex to addressTreeProof
* fix test code
> fix: fix address tree verification

- contracts/Predicate/Atomic/IsContainedPredicate.sol
- contracts/Predicate/Atomic/IsValidSignaturePredicate.sol
- contracts/Predicate/ForAllSuchThatQuantifier.sol
- contracts/Utils.sol
- test/ForAllSuchThatQuantifier.test.ts
- test/helpers/utils.ts
- test/predicate/atomic/IsValidSignaturePredicate.test.ts
- test/predicate/standard/IsValidStateTransitionPredicate.test.ts
variable has prefix V and constant value has prefix C and both legth is less than 20.
refer to cryptoeconomicslab/wakkanay#143
> fix encoding of inputs

- contracts/DepositContract.sol
> clean: clean deposit method #83

- contracts/DepositContract.sol
Reverts cryptoeconomicslab/ovm-contracts#84
> Revert "clean: clean deposit method #83"

- contracts/DepositContract.sol
- test/DepositContract.test.ts
- test/helpers/getTransactionEvent.ts
check parameters of CheckpointFinalized.
> test: fix deposit test code

- contracts/Predicate/plasma/OwnershipPredicate.ovm
- contracts/Predicate/plasma/StateUpdatePredicate.ovm
- package-lock.json
- package.json
- scripts/InitializationConfig.ts
- scripts/compileProperties.ts
- scripts/deploy.ts
I will add test code generated by compiler.
> feat: add StateUpdatePredicate and OwnershipPredicate

- contracts/DepositContract.sol
- contracts/Predicate/plasma/OwnershipPayout.sol
- scripts/deploy.ts
- test/predicate/plasma/OwnershipPayout.test.ts
> feat: add OwnershipPayout #52

- contracts/DepositContract.sol
Only payout contract can call finalizeExit.
> fix: check payout contract address

- contracts/UniversalAdjudicationContract.sol
> clean: clean adjudication contract

- contracts/Predicate/plasma/CheckpointPredicate.ovm
- contracts/Predicate/plasma/ExitPredicate.ovm
- contracts/Predicate/plasma/IncludedWithinPredicate.ovm
- contracts/Predicate/plasma/OwnershipPredicate.ovm
- contracts/Predicate/plasma/StateUpdatePredicate.ovm
- contracts/Predicate/plasma/lib/IncludedAt.ovm
- contracts/Predicate/plasma/lib/LessThan.ovm
- contracts/Predicate/plasma/lib/SignedBy.ovm
- package-lock.json
- package.json
- scripts/InitializationConfig.ts
- scripts/compileProperties.ts
- scripts/deploy.ts
- test/CommitmentContract.test.ts
- test/ForAllSuchThatQuantifier.test.ts
updating predicates
```
{"logicalConnectiveAddressTable":{"Not":"0xcE728368EE4C3fB7Da0aC5f4b1738905BBB0d1F4","And":"0x96a08824f87070075262dbce23C6bAbffDCa0493","ForAllSuchThat":"0x90FBC44Fc6f93b773D0111B830bb27CD42292C9F"},"atomicPredicateAddressTable":{"IsValidSignature":"0x17647EF21C6Fd7e67486C57afFbb1faF9EB30Ea5","IsContained":"0x4B31c27826C810007749860be339ECC28f56fb1b","IsLessThan":"0xb7c3575b27526765b617ab97125215a880d014e0","Equal":"0x4d06c05cee17b82ced7adc442c3d4f8627873de3","VerifyInclusion":"0x8d32d7a4d36f767ea29f8c0e96396f5594edf90f","IsSameAmount":"0xb3542dcfc138449a0580c16622bb33c5d9fc76d0"},"deployedPredicateTable":{"StateUpdatePredicate":{"deployedAddress":"0x4AC562dbcba73fAe01f6E74773183Cc394F98512","source":[{"type":"CompiledPredicate","name":"StateUpdate","inputDefs":["to …
```
> fix: update predicates

- contracts/DataTypes.sol
- contracts/DepositContract.sol
- contracts/Library/Deserializer.sol
- contracts/Predicate/plasma/OwnershipPayout.sol
- test/DepositContract.test.ts
- test/predicate/plasma/OwnershipPayout.test.ts
Exit struct to have 
- StateUpdat
- InclusionProof
> Exit struct

- contracts/DepositContract.sol
- test/DepositContract.test.ts
- test/helpers/getTransactionEvent.ts
Add events
- DepositedRangeExtended
- DepositedRangeRemoved
and tests for that
> emit depositedRangeUpdated events and add test

- package.json
- test/predicate/plasma/OwnershipPredicateTestCase.ts
- test/predicate/plasma/StateUpdatePredicateTestCase.ts
- test/predicate/plasma/predicates.test.ts
- test/predicate/plasma/testcase.ts
Adding test cases for generated predicates.
related to https://github.com/cryptoeconomicslab/wakkanay/issues/137
> Add test cases for generated predicate contracts

- contracts/Predicate/CompiledPredicate.sol
This is child task of https://github.com/cryptoeconomicslab/wakkanay/pull/242.
> add getChild to CompiledPredicate

- contracts/Predicate/Atomic/IsStoredPredicate.sol
- contracts/Storage.sol
- contracts/test/MockStorageContract.sol
- test/predicate/atomic/IsStoredPredicate.test.ts
add `IsStoredPredicate`
add `Storage` interface
https://www.notion.so/Design-of-IsStoredPredicate-72324ee3e6064610b724d6c24a192d46
> add IsStoredPredicate

- contracts/DataTypes.sol
- contracts/DepositContract.sol
- contracts/Library/Deserializer.sol
- contracts/Predicate/plasma/CheckpointPredicate.ovm
- contracts/Predicate/plasma/ExitDepositPredicate.ovm
- contracts/Predicate/plasma/ExitPredicate.ovm
- contracts/Predicate/plasma/OwnershipPayout.sol
- contracts/test/MockDepositContract.sol
- scripts/deploy.ts
- test/DepositContract.test.ts
* checkpoints is map of bool to reduce gas cost
* decodeStateUpdateFromExitProperty check state update is subrange of finalized checkpoint for the situation to exit partial range from deposit.
> Update Deposit Contract to support exit deposit

- contracts/PlasmaETH.sol
- package-lock.json
- package.json
- test/PlasmaETH.test.ts
> unwrap peth when exit

- contracts/PlasmaETH.sol
- test/PlasmaETH.test.ts
> remove transfer function of peth contract WAK-229

- package-lock.json
- package.json
- scripts/compileProperties.ts
- scripts/deploy.ts
update Ethereum-generator to apply an optimizing option of solc.
> update ethereum generator

- contracts/DummyERC20.sol
- package.json
- scripts/InitializationConfig.ts
- scripts/configEnv.ts
- scripts/deploy.ts
- scripts/deployToken.ts
- scripts/helper.ts
- Add erc20 token deploy script
- extract deploy utils
> Deploy dummy erc20 afterwards

- scripts/deploy.ts
- scripts/deployToken.ts
change the arguments when deployed tokens. (the name is first)
```
constructor(string memory name, string memory symbol, uint8 decimals)
public
ERC20()
ERC20Detailed(name, symbol, decimals)
{}
```
https://github.com/cryptoeconomicslab/ovm-contracts/blob/master/contracts/PlasmaETH.sol#L14
> fix deploy token arguments

- package-lock.json
- package.json
This is why we could not use `before` but `beforeAll`.
> remove @types/jest and add @types/mocha

- contracts/Predicate/Atomic/IsValidSignaturePredicate.sol
- contracts/Predicate/CompiledPredicate.sol
- contracts/Predicate/TypedDataPredicate.sol
- contracts/Predicate/plasma/CheckpointPredicate.ovm
- contracts/Predicate/plasma/ExitDepositPredicate.ovm
- contracts/Predicate/plasma/ExitPredicate.ovm
- contracts/Predicate/plasma/IncludedAtPredicate.ovm
- contracts/Predicate/plasma/OwnershipPredicate.ovm
- contracts/Predicate/plasma/StateUpdatePredicate.ovm
- contracts/Predicate/plasma/lib/IncludedAt.ovm
- contracts/Predicate/plasma/lib/LessThan.ovm
- contracts/Predicate/plasma/lib/SignedBy.ovm
- contracts/test/MockOwnershipPredicate.sol
- package-lock.json
- package.json
- scripts/deploy.ts
- test/Dispute/CheckpointDispute.test.ts
- test/predicate/atomic/IsValidSignaturePredicate.test.ts
> add typedData verifierType to IsValidSignaturePredicate

- package.json
- test/Dispute/CheckpointDispute.test.ts
Added parallel option at test runtime
(Also the timeout option....)
To speed up processing by running tests in parallel
> parallel test

- contracts/Dispute/CheckpointChallengeValidator.sol
- contracts/Dispute/CheckpointDispute.sol
- contracts/Dispute/ExitDispute.sol
- contracts/Dispute/SpentChallengeValidator.sol
- contracts/Utils.sol
- test/Dispute/ExitDispute.test.ts
add test cases and fix challenge.
* remove label from challengeInputs for CheckpointChallengeVerifier
* leave out validation of challenged claim is started from CheckpointChallengeVerifier
* isSubrange -> hasIntersection for spending more than 2 state updates
> add challenge and settle test cases for ExitDispute contract
